server {
	listen	   80;
	listen  [::]:80;

	error_page 404 /404.html;

	location / {
		if ($request_uri ~ ^/(.*)\.html(\?|$)) {
			return 302 /$1;
		}
		root /usr/share/nginx/html;
		try_files $uri $uri.html $uri/ =404;
	}

	location = /repl {
			perl 'sub {
			my $r = shift;
			$r->send_http_header("text/plain");
			$r->print("Hello, World!");
			return OK;
		}';
	}
}

