server {
	listen	   80;
	listen  [::]:80;

	error_page 404 /404.html;

	location / {
		if ($request_uri ~ ^/(.*)\.html(\?|$)) {
			return 302 /$1;
		}
		root /usr/share/nginx/html;
		try_files $uri $uri.html $uri/ =404;
	}

	location = /repl {
		perl 'sub {
			my $r = shift;

			if ($r->request_method ne "POST") {
				return DECLINED;
			}

			if ($r->has_request_body(\&handler)) {
				return OK;
			}

			sub handler {
				my $r = shift;
				my $c = $r->request_body;

				my $b = "echo \'${c}\' | /usr/share/nginx/bin/repl -q";
				my $o = `${b}`;

				$r->send_http_header;
				$r->print($o);
				return OK;
			}

			return HTTP_BAD_REQUEST;
		}';
	}
}

