name: Continuous Integration v2.x

#trigger when these occur
on:
  push:
    branches:
      - v2
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - v2
  workflow_dispatch:

#CI workflows, limited coverage atm
jobs:
  units:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preinstall dependencies
        run: sudo apt update && sudo apt install gdb
      - name: Run the tests
        run: make tests
      - name: Run the tests under gdb
        run: make tests-gdb
