name: Continuous Integration v2.x

#trigger when these occur
on:
  push:
    branches:
      - v2
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - v2
  workflow_dispatch:

#CI workflows, limited coverage atm
jobs:
  standard:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Updates
        run: sudo apt update && sudo apt upgrade -y
      - name: Run all tests
        run: make tests
  gdb:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Updates
        run: sudo apt update && sudo apt upgrade -y
      - name: Install GDB if not present
        run: sudo apt install gdb
      - name: Run all tests under gdb
        run: make tests-gdb